#!/bin/bash
set -euo pipefail
export USER="JohnDoe"
export PASSWORD="Welcome@123"
steps:
- label: ":hammer: Tests"
  command: echo $USER $PASSWORD
  plugins:
    docker#v3.5.0:
      user: root
      image: ubuntu
